[package]
name = "torrent-rs"
version = "0.1.0"
authors = ["zhangguyu6 <zhangguyu6@gmail.com>"]
edition = "2018"


[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
serde_bytes = "0.11"
